# General
baseurl: ''
name: "kandr3s"
logo: "images/kandr3s.jpg"
author: "kandr3s"
tagline: "🇨🇴 Programmer. Minimalist. Autodidact."

# SEO
description: "Personal website of @kandr3s."
twitter: 
  username: kandr3s
  card: summary

# Exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-feed   
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-last-modified-at

# Sass 
sass:
  sass_dir: assets
  style: compressed