# General
url: "https://kandr3s.co"
baseurl: ''
name: "kandr3s' webpage"
image: "images/kandr3s.jpg"
author: "kandr3s"

# SEO
description: "Updates from @kandr3s. 🇨🇴 Programmer. Minimalist. Autodidact."
twitter: 
  username: kandr3s
  card: summary 

# Exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:categories/:title

plugins:
  - jekyll-seo-tag
  - jekyll-feed   
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-last-modified-at

# Sass 
sass:
  sass_dir: assets
  style: compressed