# General
baseurl: ''
name: "Andrés Cárdenas"
logo: "/images/kandr3s.jpg"
author: "kandr3s"
tagline: "🇨🇴 Autodidact."

# SEO
description: "Personal website of @kandr3s [Andrés Cárdenas]"
twitter: 
  username: kandr3s
  card: summary

# Exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-feed   
  - jekyll-sitemap
  - jekyll-redirect-from

# Sass 
sass:
  sass_dir: assets
  style: compressed