# general configuration
url: http://kandr3s.co
baseurl: ''
name: "kandr3s"
logo: "/images/kandr3s.jpg"
# author will appear under the avatar (optional)
author: "kandr3s"
# tagline will appear under the title (optional)
tagline: "Web journal."
twitter: "kandr3s"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-feed   
  - jekyll-sitemap

# Sass 
sass:
  sass_dir: assets
  style: compressed